Inv_Informatico/Inv_Informatico.WebAdmin/Controllers/BodegasController.cs
using Inv_Informatico.BL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Inv_Informatico.WebAdmin.Controllers
{
    public class BodegasController : Controller
    {
        BodegasBL _bodegasBL;

        public BodegasController()
        {
            _bodegasBL = new BodegasBL();
        }

        // GET: Bodegas
        public ActionResult Index()
        {
            var listadeBodegas = _bodegasBL.ObtenerBodegas();

            return View(listadeBodegas);
        }

        public ActionResult Crear()
        {
            var nuevaBodega = new Bodega();

            return View(nuevaBodega);
        }

        [HttpPost]
        public ActionResult Crear(Bodega bodega)
        {
            if (ModelState.IsValid)
            {
                if (bodega.Descripcion != bodega.Descripcion.Trim())
                {
                    ModelState.AddModelError("Descripcion", "La descripción no debe contener espacios al inicio o al final");
                    return View(bodega);
                }

                _bodegasBL.GuardarBodega(bodega);

                return RedirectToAction("Index");
            }

            return View(bodega);
        }

        public ActionResult Editar(int id)
        {
            var bodega = _bodegasBL.ObtenerBodega(id);

            return View(bodega);
        }

        [HttpPost]
        public ActionResult Editar(Bodega bodega)
        {
            if (ModelState.IsValid)
            {
                if (bodega.Descripcion != bodega.Descripcion.Trim())
                {
                    ModelState.AddModelError("Descripcion", "La descripción no debe contener espacios al inicio o al final");
                    return View(bodega);
                }

                _bodegasBL.GuardarBodega(bodega);

                return RedirectToAction("Index");
            }

            return View(bodega);
        }

        public ActionResult Detalle(int id)
        {
            var bodega = _bodegasBL.ObtenerBodega(id);

            return View(bodega);
        }

        public ActionResult Eliminar(int id)
        {
            var bodega = _bodegasBL.ObtenerBodega(id);

            return View(bodega);
        }

        [HttpPost]
        public ActionResult Eliminar(Bodega bodega)
        {
            _bodegasBL.EliminarBodega(bodega.Id);

            return RedirectToAction("Index");
        }
    }
}

Inv_Informatico/Inv_Informatico.WebAdmin/Controllers/CategoriasController.cs
using Inv_Informatico.BL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Inv_Informatico.WebAdmin.Controllers
{
    public class CategoriasController : Controller
    {
        CategoriasBL _CategoriasBL;

        public CategoriasController()
        {
            _CategoriasBL = new CategoriasBL();
        }
        // GET: Categorias
        public ActionResult Index()
        {
            var listadeCategorias = _CategoriasBL.ObtenerCategoria();
            return View(listadeCategorias);
        }

        public ActionResult Crear()
        {
            var nuevaCategoria = new Categoria();

            return View(nuevaCategoria);
        }

        [HttpPost]
        public ActionResult Crear(Categoria categoria)
        {
            if(ModelState.IsValid)
            {
                if (categoria.Descripcion != categoria.Descripcion.Trim())
                {
                    ModelState.AddModelError("Descripcion", "No ingrese espacios en blanco");
                    return View(categoria);
                }
                    _CategoriasBL.GuardarCategoria(categoria);
                return RedirectToAction("Index");
            }

            return View(categoria);
        }

        public ActionResult Editar(int id)
        {
            var categoria = _CategoriasBL.ObtenerCategoria(id);

            return View(categoria);
        }

        [HttpPost]
        public ActionResult Editar(Categoria categoria)
        {
            if (ModelState.IsValid)
            {
                if (categoria.Descripcion != categoria.Descripcion.Trim())
                {
                    ModelState.AddModelError("Descripcion", "No ingrese espacios en blanco");
                    return View(categoria);
                }
                _CategoriasBL.GuardarCategoria(categoria);
                return RedirectToAction("Index");
            }

            return View(categoria);
        }

        public ActionResult Detalle(int id)
        {
            var categoria = _CategoriasBL.ObtenerCategoria(id);

            return View(categoria);

        }
        public ActionResult Eliminar(int id)
        {
            var categoria = _CategoriasBL.ObtenerCategoria(id);

            return View(categoria);

        }
        [HttpPost]
        public ActionResult Eliminar(Categoria categoria)
        {
            _CategoriasBL.EliminarCategoria(categoria.id);
            return RedirectToAction("Index");
        }
    }
    }

Inv_Informatico/Inv_Informatico.WebAdmin/Controllers/UbicacionesController.cs
using Inv_Informatico.BL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Inv_Informatico.WebAdmin.Controllers
{
     public class UbicacionesController : Controller
    {
        UbicacionesBL _UbicacionesBL;
        BodegasBL _BodegasBL;

        public UbicacionesController()
        {
            _UbicacionesBL = new UbicacionesBL();
            _BodegasBL = new BodegasBL();
        }

        // GET: Ubicaciones
        public ActionResult Index()
        {
            var listadeUbicaciones = _UbicacionesBL.ObtenerUbicacion();

            return View(listadeUbicaciones);
        }

        public ActionResult Crear()
        {
            var nuevoUbicacion = new Ubicacion();
            var bodegas = _BodegasBL.ObtenerBodegas();
            ViewBag.ListaBodegas = new SelectList(bodegas, "Id", "Descripcion");

            return View(nuevoUbicacion);
        }

        [HttpPost]
        public ActionResult Crear(Ubicacion ubicacion)
        {

            var bodegas = _BodegasBL.ObtenerBodegas();
            ViewBag.ListaBodegas= new SelectList(bodegas, "Id", "Descripcion");

            return View(ubicacion);

        }

        public ActionResult Editar(int Id)
        {
            var ubicacion = _UbicacionesBL.ObtenerUbicacion(Id);
            var bodegas = _BodegasBL.ObtenerBodegas();

            ViewBag.BodegaId = new SelectList(bodegas, "id", "Descripcion", ubicacion.BodegaId);

            return View(ubicacion);
        }

        [HttpPost]
        public ActionResult Editar(Ubicacion ubicacion)
        {
            if (ModelState.IsValid)
            {
                _UbicacionesBL.GuardarUbicacion(ubicacion);
                return RedirectToAction("Index");   
            }
            var bodegas = _BodegasBL.ObtenerBodegas();

           ViewBag.BodegaId =
           new SelectList(bodegas, "Id", "Descripcion");

           return View(ubicacion);
        }

        public ActionResult Detalle(int id)
        {
            var ubicacion = _UbicacionesBL.ObtenerUbicacion(id);

            return View(ubicacion);
        }

        public ActionResult Eliminar(int id)
        {
            var ubicacion = _UbicacionesBL.ObtenerUbicacion(id);

            return View(id);
        }

        [HttpPost]
        public ActionResult Eliminar(Ubicacion ubicacion)
        {
            _UbicacionesBL.EliminarUbicacion(ubicacion.Id);

            return RedirectToAction("Index");
        }

    }
}

Inv_Informatico/Inv_Informatico.WebAdmin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Inventario Informatico</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>
                        @Html.ActionLink("Inicio", "Index", "Home")
                    </li>
                    <li>
                        @Html.ActionLink("Hardware", "Index", "Hardware")
                    </li>
                    <li>
                        @Html.ActionLink("Categoria", "Index", "Categorias")
                    </li>
                    <li>
                        @Html.ActionLink("Bodega", "Index", "Bodegas")
                    </li>
                    <li>
                        @Html.ActionLink("Ubicacion", "Index", "Ubicaciones")
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Inventario Informatico</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>