Inv_Informatico/Inv_Informatico.WebAdmin/Controllers/HardwareController.cs
using Inv_Informatico.BL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Inv_Informatico.WebAdmin.Controllers
{
    public class HardwareController : Controller
    {
        HardwareBL _HardwareBL;
        CategoriasBL _CategoriasBL;

        public HardwareController()
        {
            _HardwareBL = new HardwareBL();
            _CategoriasBL = new CategoriasBL();
        }
        // GET: Productos
        public ActionResult Index()
        {
            var listaHardware = _HardwareBL.ObtenerHardware(); 
            return View(listaHardware );
        }

     
        public ActionResult Crear()
        {
            var nuevoHardware = new Hardware();
            var categorias = _CategoriasBL.ObtenerCategoria();
            ViewBag.ListaCategorias = new SelectList(categorias, "id", "Descripcion");

            return View(nuevoHardware);
        }

       [HttpPost]
        public ActionResult Crear(Hardware hardware, HttpPostedFileBase imagen)
        {
            if(ModelState.IsValid)
            {
                if(imagen != null)
                {
                    hardware.UrlImagen = GuardarImagen(imagen);
                }

                _HardwareBL.GuardarHardware(hardware);

                return RedirectToAction("Index");
            }
            var categorias = _CategoriasBL.ObtenerCategoria();
            ViewBag.ListaCategorias = new SelectList(categorias, "id", "Descripcion");

            return View(hardware);
        }

        public ActionResult Editar(int id)
        {
            var hardware = _HardwareBL.ObtenerHardware(id);
            var categorias = _CategoriasBL.ObtenerCategoria();
            ViewBag.Categoriaid = new SelectList(categorias, "id", "Descripcion",hardware.Categoriaid);
            return View(hardware);
        }

        [HttpPost]
        public ActionResult Editar(Hardware hardware)
        {
            if (ModelState.IsValid)
            {
                _HardwareBL.GuardarHardware(hardware);

                return RedirectToAction("Index");
            }
            var categorias = _CategoriasBL.ObtenerCategoria();
            ViewBag.ListaCategorias = new SelectList(categorias, "id", "Descripcion");

            return View(hardware);
        }

        public ActionResult Detalle(int id)
        {
            var hardware = _HardwareBL.ObtenerHardware(1);
            return View(1);
        }


        public ActionResult Eliminar(int id)
        {
            var producto = _HardwareBL.ObtenerHardware(id);
            return View(id);
        }

        [HttpPost]
        public ActionResult Eliminar(Hardware hardware)
        {
            _HardwareBL.EliminarHardware(hardware.Id);
            return RedirectToAction ("Index");
        }

        private string GuardarImagen(HttpPostedFileBase imagen)
        {
            string paht = Server.MapPath("~/Imagenes/" + imagen.FileName);
                imagen.SaveAs(paht);

            return "/Imagenes/" + imagen.FileName;
        }

    }
}

Inv_Informatico/Inv_Informatico.WebAdmin/Views/Hardware/Crear.cshtml
@model Inv_Informatico.BL.Hardware

@{
    ViewBag.Title = "Crear";
}

<h2>Crear</h2>


@using (Html.BeginForm("Crear", "Hardware", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Hardware</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Categoria, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ListaCategorias", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Categoria, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
              <label class="control-label col-md-2">Seleccionar imagen</label>
            <div class="col-md-10">
                <input type="file" name="imagen" id="imagen"/> 
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Marca, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Marca, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Marca, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Inv_Informatico/Inv_Informatico.WebAdmin/Views/Hardware/Detalle.cshtml
@model Inv_Informatico.BL.Hardware

@{
    ViewBag.Title = "Detalle";
}

<h2>Detalle</h2>

<div>
    <h4>Hardware</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descripcion)
        </dd>

        <dd>
            @Html.DisplayNameFor(model => model.Categoria)
        </dd>

        <dd>
            @Html.DisplayFor(model => model.Categoria.Descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UrlImagen)
        </dt>

        <dd>
            <img src="@Model.UrlImagen" alt="@Model.Descripcion" style="width:200px; height:auto;" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Marca)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Marca)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Inv_Informatico/Inv_Informatico.WebAdmin/Views/Hardware/Editar.cshtml
@model Inv_Informatico.BL.Hardware

@{
    ViewBag.Title = "Editar";
}

<h2>Editar</h2>


@using (Html.BeginForm("Editar", "Hardware", FormMethod.Post, new { enctype = "multipart/form-data" } ))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Hardware</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Categoria,"Categoria", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ListaCategoriaid", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Categoriaid, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Seleccionar imagen</label>
            <div class="col-md-10">
                <input type="file" name="imagen" id="imagen" />
            </div>
            <div class="col-md-8">
                img src="@Model.UrlImagen" alt="@Model.Descripcion" style="width:200px; height:auto;" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Marca, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Marca, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Marca, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Inv_Informatico/Inv_Informatico.WebAdmin/Views/Hardware/Eliminar.cshtml
@model Inv_Informatico.BL.Hardware

@{
    ViewBag.Title = "Eliminar";
}

<h2>Eliminar</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Hardware</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>

        <dd>
            @Html.DisplayNameFor(model => model.Categoria)
        </dd>

        <dd>
            @Html.DisplayFor(model => model.Categoria.Descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Marca)
        </dt>

        <dt>
            @Html.DisplayNameFor(model => model.UrlImagen)
        </dt>

        <dd>
            <img src="@Model.UrlImagen" alt="@Model.Descripcion" style="width:200px; height:auto;" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Marca)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Marca)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Inv_Informatico/Inv_Informatico.WebAdmin/Views/Hardware/Index.cshtml
@model IEnumerable<Inv_Informatico.BL.Hardware>

@{
    ViewBag.Title = "Hardware";
}

<h2>Hardware</h2>

<p>
    @Html.ActionLink("Nuevo Hardware", "Crear")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Descripcion)
        </th>

        <th>@Html.DisplayNameFor(model => model.UrlImagen)</th>

        <th>
            @Html.DisplayNameFor(model => model.Marca)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Descripcion)
        </td>

        <td>
            <img src="@item.UrlImagen" alt="@item.Descripcion" style="width:64px; height:auto;" />
        </td>

        <td>
            @Html.DisplayFor(modelItem => item.Marca)
        </td>
        <td>
            @Html.ActionLink("Editar", "Editar", new { id=item.Id }) |
            @Html.ActionLink("Detalles", "Detalles", new { id=item.Id }) |
            @Html.ActionLink("eliminar", "eliminar", new { id=item.Id })
        </td>
    </tr>
}

</table>